services:
    app:
        container_name: fw_intranet
        build:
            context: .
        ports:
          -  "5111:5000"
        volumes:
            -   type: bind
                source: .
                target: /home
# volumes:
#     myapp: