# version: '3.9'

# networks:
#   intranetwork:
#     driver: bridge
#     external: true

services:
    app:
      container_name: fw_intranet
      build:
          context: .
      ports:
          -  "5111:5000"
      # networks:
      #   - intranetwork
